feet: Reword spoonfeed command to be nice
Qbox-project/Qbot pull request #3
Opened 2024-12-03 01:57 UTC by Sharkiiie

It's nice now.

2024-12-03 01:59 UTC, mafewtm approved these changes

2024-12-03 02:27 UTC, Manason approved these changes

2024-12-03 05:26 UTC, thelindat requested changes
fivem devs don't deserve kindness
revert

2024-12-17 22:34 UTC, D4isDAVID approved these changes

2024-12-17 22:35 UTC, merged